# Generated by Django 4.0 on 2022-01-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zoe', models.CharField(max_length=40)),
                ('Aldana', models.CharField(max_length=40)),
                ('Tamara', models.CharField(max_length=40)),
                ('Mateo', models.CharField(max_length=40)),
                ('Juan', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Esculpidas', models.CharField(max_length=40)),
                ('Kapping', models.CharField(max_length=40)),
                ('Tintura', models.CharField(max_length=40)),
                ('Corte', models.CharField(max_length=40)),
                ('Peinado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=40)),
                ('dia', models.IntegerField()),
                ('hora', models.IntegerField()),
            ],
        ),
    ]
