# Generated by Django 4.0.1 on 2022-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('servicio', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='inicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='profesionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Zoe', models.CharField(max_length=40)),
                ('Aldana', models.CharField(max_length=40)),
                ('Tamara', models.CharField(max_length=40)),
                ('Mateo', models.CharField(max_length=40)),
                ('Juan', models.CharField(max_length=40)),
                ('Maria', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manicura', models.CharField(max_length=40)),
                ('Masajes', models.CharField(max_length=40)),
                ('Color_y_corte', models.CharField(max_length=40)),
                ('Pestañas', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Profesional',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
        migrations.DeleteModel(
            name='Sucursal',
        ),
        migrations.DeleteModel(
            name='Turno',
        ),
    ]
