# Generated by Django 4.0 on 2022-02-21 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_consulta_inicio_profesionales_servicios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesionales',
            old_name='Aldana',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='profesionales',
            old_name='Juan',
            new_name='nombreDeProfesional',
        ),
        migrations.RenameField(
            model_name='profesionales',
            old_name='Maria',
            new_name='turno',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Color_y_corte',
            new_name='detalleDeServicio',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Manicura',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='servicios',
            old_name='Masajes',
            new_name='servicio',
        ),
        migrations.RemoveField(
            model_name='profesionales',
            name='Mateo',
        ),
        migrations.RemoveField(
            model_name='profesionales',
            name='Tamara',
        ),
        migrations.RemoveField(
            model_name='profesionales',
            name='Zoe',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='Pestañas',
        ),
    ]
