# Generated by Django 4.0.1 on 2022-03-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_post_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesionalesForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
