# Generated by Django 4.0.1 on 2022-03-01 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_profesionalesform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfesionalesForm',
        ),
    ]
